mockup for applicaiton summary page completed
bcgov/ECC-ECER pull request #267
Opened 2024-05-15 18:35 UTC by SoLetsDev

## Title
ECER-1683: Brief description of the changes

## Description

-router addition and also new page for application summary

## Checklist
- [ ] I have tested these changes locally.
- [ ] Changes to backend endpoints are covered by passing integration tests.
- [ ] I have added or updated the necessary documentation.

## Screenshots (if applicable)
![image](https://github.com/bcgov/ECC-ECER/assets/74216496/70f3c4e1-a6cb-4c90-8ab9-64332e7122d6)

2024-05-15 18:59 UTC, pcatkins commented on src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationSummary.vue
> +.test {
Do we need this?

2024-05-15 18:59 UTC, pcatkins requested changes
Small clean up.

2024-05-15 19:54 UTC, SoLetsDev commented on src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/ApplicationSummary.vue
> +.test {
.test .... nope haha damn. nice catch

2024-05-15 20:38 UTC, pcatkins commented on src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/router.ts
> +      path: "/application/summary",
suggesting we go with `/manage-application`, the way it is now feels like a child route of application. Thoughts?

2024-05-16 06:33 UTC, pcatkins approved these changes

2024-05-16 14:29 UTC, merged