Ecer 734
bcgov/ECC-ECER pull request #37
Opened 2024-01-18 23:06 UTC by SoLetsDev

Adding in mobile view for certifications. Added title to certifications page.

2024-01-19 19:16 UTC, pcatkins requested changes
@SoLetsDev can we attempt to model the url route to expansion panel state? Would be nice to use the same routes as desktop. 

I.e. 
`{base_url}/my-certification/in-progress` -> In Progress v-expansion-panel is open, 
`{base_url}/my-certification/completed` -> Completed v-expansion-panel is open

I also think the router currently auto pushes from `{base_url}/my-certification` to `{base_url}/my-certification/in-progress` so that is misleading when we have the Completed expansion panel open...

2024-01-19 21:41 UTC, SoLetsDev reviewed
Changed it so that we are changing the URL when going through the expansion panels also the panel will pop open when we need it to. 

ex. in-progress will pop open the 1st expansion panel.

2024-01-22 16:47 UTC, pcatkins commented on src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client/src/components/CertificationTabs.vue
> +      return this.$route.name === "in-progress" ? 0 : 1;
@SoLetsDev _Nitpick_... could use an enum?

`enum CertificationTab {
  INPROGRESS = 0,
  COMPLETED = 1,
}`

2024-01-22 16:47 UTC, pcatkins approved these changes

2024-01-22 20:23 UTC, pcatkins approved these changes

2024-01-22 21:11 UTC, merged