Tasks/ecer 2513
bcgov/ECC-ECER pull request #386
Opened 2024-07-19 17:30 UTC by SoLetsDev

ECER-2513: frontend is able to view certificate pdf. 

## Description

- Able to view certificate

## Checklist
- [x] I have tested these changes locally.
- [ ] Changes to backend endpoints are covered by passing integration tests.
- [ ] I have added or updated the necessary documentation.

## Screenshots (if applicable)
![image](https://github.com/user-attachments/assets/48ac5ab9-2bfe-4154-8b19-54c0a52ac4a0)

interesting behavior where print dialog pops up automatically. 
![image](https://github.com/user-attachments/assets/5634377b-78c0-4a6f-9924-9c35aaac664f)

2024-07-29 15:17 UTC, farzadnadiri commented
Do we want to show the print dialog box directly? Or is it better to show the PDF first?

2024-07-29 15:24 UTC, SoLetsDev commented
@farzadnadiri Yeah ideally we don't want to show the print dialog ... not sure why that's happening. 

Would like to explore some solutions. Maybe change the response header to attachment; inline ?

2024-07-30 16:49 UTC, pcatkins requested changes
Small change to handle loading on dashboard

2024-07-31 20:36 UTC, pcatkins approved these changes

2024-07-31 20:37 UTC, merged