Communication repository refactor
bcgov/ECC-ECER pull request #469
Opened 2024-08-30 19:50 UTC by farzadnadiri

- Communication repository refactor
## Related Jira Issue(s)

- ECER-2927
- etc.

## Checklist
- [ ] I have tested these changes locally.
- [ ] Changes to backend endpoints are covered by passing integration tests.
- [ ] I have added or updated the necessary documentation.

2024-08-30 19:51 UTC, farzadnadiri commented on src/ECER.Resources.Accounts/Communications/CommunicationRepository.cs
> +    var communications = context.ecer_CommunicationSet;
decoupled applications as we don't need them here.

2024-08-30 21:02 UTC, qsl-deepak commented on src/ECER.Resources.Accounts/Communications/CommunicationRepository.cs
> +      TotalMessagesCount = query.PageNumber > 0 ? paginatedTotalCommunicationCount : finalCommunications.Count,
Need to set "UnreadMessagesCount" here

2024-08-30 21:06 UTC, qsl-deepak commented on src/ECER.Resources.Accounts/Communications/CommunicationRepository.cs
> +      communications = communications.Where(item => item.ecer_ParentCommunicationid.Id == Guid.Parse(query.ByParentId) && item.ecer_IsRoot != true);
Should get rid of " && item.ecer_IsRoot != true" here, otherwise base parent message will not get displayed in message thread

2024-08-30 21:29 UTC, qsl-deepak requested changes
A few points to consider:

1) Unread message count should return total count of parent + any child messages(we show the count of unread messages on the dashboard)

2) Parent communication need to be sorted based on latest activity on that communication ( i.e latest message - based on parent or child message date time should be shown first)

3) Parent message should show date time of latest message in that thread (based on parent or child message date time) 

4) Pagination should take care of message sorting i.e latest parent communication (based on parent or child date time) should bubble up on the top before pagination can be applied

5) Child messages in the thread should be sorted in descending order (latest communication in the thread should be displayed first)

2024-09-03 21:56 UTC, farzadnadiri commented
Worked with Deepak on it, it's ready now but we just need to ask dynamics to set ecer_LatestMessageNotifiedDate to utcnow when they create a communication.

2024-09-09 20:41 UTC, qsl-deepak approved these changes

2024-09-09 20:41 UTC, merged